cat_features:
  - workclass
  - education
  - marital-status
  - occupation
  - relationship
  - race
  - sex
  - native-country
random_forest:
  random_state: 42
  n_estimators: 100
  max_depth: 15
  min_samples_split: 4
  min_samples_leaf: 3
  n_jobs: -1

